### ISSUE TITLE
Harvester with Agricraft :)

### ISSUE THREAD

**Issue by GrantiMC** [Lothrazar/Cyclic#1008]
Minecraft version & Mod Version:
1.12.2 / 1.17.10

Hey :) is there a way to use the Harvester with the Agricraft Crop Sticks?

**Comment by Lothrazar** [comment]
There might not be an easy way, since it uses crop sticks.  needs investigation

note to self Latest stable build is a6 here https://minecraft.curseforge.com/projects/agricraft/files/2609648

**Comment by Lothrazar** [comment]
Agricraft is too custom and too unique to work together with this, i feel like this would need changes on their end, maybe an API or some docs, or a third party mod to work.  Or if anyone wants to make a PR for this that would be great but i dont see any easy solution on my end.    


Plus Agricraft seems to have been POSSIBLY abandoned, due to their issue tracker being ignored since august 2018 so im not very motivated.

Ill leave it open with a help wanted tag

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle.  Also agricraft is still  stale and untouched since August, 2018

**Comment by Hornblower409** [comment]
Automated Users **DO** work with AgriCraft 1.12 Crop Sticks

For any other poor souls who find themselves here - Cyclic Automated User does work for gently harvesting AgriCraft 1.12 blocks with Crop Sticks. Give it some power, but don't give it any tools, and set the mode to "Use". It will "use" each block in it's range and make the crop drop. Cyclic Item Collector can then be used to pick up the fruits of your labor.
