### ISSUE TITLE
Hydrator top left only

### ISSUE THREAD

**Issue by ThePoet444** [Lothrazar/Cyclic#1042]
Minecraft version & Mod Version: MC 1.12.2 & Cyclic 1.17.14

Single player or Server: Single

Describe problem (what you were doing / what happened):
Trying to make gray concrete, and the hydrator will only work if the powder is in the top left slot only. Other slots won't output finished product. 

Crash log (if any): none

**Comment by Lothrazar** [comment]
Yeah it should be shapeless and take from any slot, or at least move them over

**Comment by Lothrazar** [comment]
Oh I remember running into this exact thing before which is why I added that lock button. So the recipe has to match exact just like a crafting table meaning one powder and three empty.  So to block automation such as hoppers using the wrong slot, close the lock and it will only refil the top left

![lock icon](https://user-images.githubusercontent.com/621529/51435027-21528500-1c23-11e9-9f70-59a61e47a904.gif)

**Comment by ThePoet444** [comment]
I mean, I was hoping to dump a bunch of stacks of concrete powder in there and just let it run to make concrete, but if it only works in the top left, then so be it. I'll just have to get creative with automation.

**Comment by Lothrazar** [comment]
Yep even just a full double chest and a hopper, then just the one slot and three empty that will work

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2663412
