### ISSUE TITLE
1.12.2 Excavation Enchant deleting Bonsai Pots and contents 

### ISSUE THREAD

**Issue by MechaDom** [Lothrazar/Cyclic#1063]
Minecraft version & Mod Version: 
Minecraft 1.12.2 Forge 14.23.5.2808
Cyclic 1.12.2-1.17.16

Single player or Server:
Server

Describe problem (what you were doing / what happened):
When mining Bonsai Pots, Excavation activates and destroys the Bonsai pots instead of dropping them.  Also destroys the dirt and sapling

**Comment by Lothrazar** [comment]
Am i doing this right? When i do this it just mines one block and excavation doesnt even go.


It wont let me put dirt or saplings into it

![asdfasdfasdf](https://user-images.githubusercontent.com/621529/53289313-63527780-3749-11e9-9f11-d3d247f6dbb9.gif)

**Comment by MechaDom** [comment]
Excavation goes on an Axe for this to work in this manner

**Comment by Lothrazar** [comment]
Still happening on new versions; but i dont have any way to fix it on my end. excavate works with pickaxes and axes on other modded machines, and for example axes on chests.

The enchantment calls varios common hooks including "harvestBlock" so that would be a starting point on their end
https://github.com/Lothrazar/Cyclic/blob/6b158e09b3bf4906dd161d48329f010d9cbd2741/src/main/java/com/lothrazar/cyclicmagic/enchant/EnchantExcavation.java#L127
