### ISSUE TITLE
Packager Fps and Tps Issues {especially when full and not able to process}

### ISSUE THREAD

**Issue by Bennyboy1695** [Lothrazar/Cyclic#1109]
Minecraft Version: 1.12.2

Forge Version: 2831

Mod Version: 1.19.3

Single Player or Server: Server

Describe problem (what you were doing / what happened):
When the packagers input is full the packager can cause some big fps and tps issues.

Log file (text block or link):
`[20:56:52] [Client thread/WARN] [net.minecraft.profiler.Profiler]: Something's taking too long! 'root.tick.level.entities.blockEntities.minecraft:auto_packager_te' took aprox 102.762145 ms`
Logs of a tickprofiler profile done before the packagers were removed - https://hastebin.com/ajonalubox.md

Video/images: (links are great; github also allows up to 10MB with direct drag and drop; gifs using https://www.screentogif.com/)

**Comment by i9hdkill** [comment]
Cyclic-1.12.2-1.19.8.jar
Can't add that much information, but looked into it with LagGoggles and found this:

I ran a scan for 20 seconds and it showed me these results:
![Screenshot_3](https://user-images.githubusercontent.com/4679374/58601001-2dacb580-8287-11e9-95b3-aae40a6e2ac3.jpg)

As you may know, red blocks with high numbers are the bad boys:
![Screenshot_4](https://user-images.githubusercontent.com/4679374/58601016-4026ef00-8287-11e9-91ee-1e1048217ca9.jpg)

**Comment by Yorkforce** [comment]
Were seeing this alot on our servers too, if the input slot is full the TPS plummets, a single stuffed packager can make the server unplayable.

Maybe add an overflow slot that deletes anything going into it, with maybe a config option to enable/disable?

**Comment by Lothrazar** [comment]
I see, sounds like perhaps there is an issue specifically when it is full and trying to process

**Comment by Lothrazar** [comment]
Please create an NPS sample so it cans pecifiy which lines of code are actualy causing the lang in the minecraftServer.run thread  
https://minecraft.curseforge.com/projects/sampler

**Comment by zjeffer** [comment]
@Lothrazar I have the same problem: packagers are taking about 20k microseconds/tick according to LagGoggles after a 30 second scan. They're not full because I use a filter to limit the amount of items in them to 64.

I made a report using the sampler you linked: 
[sampler-snapshot.zip](https://github.com/Lothrazar/Cyclic/files/3390053/sampler-snapshot.zip)

Also, when looking though LagGoggles, it seems like pretty much all of Cyclic's machines have a higher value than other mods: Solidifier and Hydrator both use about 400 (at idle!). Machines from other mods like Mekanism or Nuclearcraft use like 10, maximum. Bonsai trees use about 100-200 with yellow mulch, about 10 with normal dirt. 

I hope this helps with the issue.

**Comment by Lothrazar** [comment]
I know youve probably moved on to other things since i took so long.  The sample you uploaded did identify a part where it was taking two and a half seconds moving items in an out of a recipe container where it didnt need to be doing it.

**Comment by Lothrazar** [comment]
On the other machines. Solidifier in this sample is taking 82 ms, so more accurate and not as bad as the lag goggles 400. but ill go through them all anyway.  For example, if its turned off by redstone, or if all item slots are empty, skip doing all the work.  The most expensive thing is pretty much always trying to find a new recipe when the item slots change , and looking to match a recipe when everythings empty is a waste

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/cyclic/files/2852262
