### ISSUE TITLE
Dupe Interaction: Filing Cabinet and Cyclic Item Transfer Node

### ISSUE THREAD

**Issue by LezChap** [Lothrazar/Cyclic#1119]
I'm using version realfilingcabinet-1.12.1-0.1.84 in Sky Factory 4.0.2.  Cyclic version Cyclic-1.12.2-1.19.4.  Cross posted: https://github.com/bafomdad/realfilingcabinet/issues/70

## Summary: 
Transferring items into a Filing Cabinet from a Cyclic Item Transfer Node (Wireless) keeps the item it's trying to move, while also duping the item into the Filing Cabinet.
Maybe related to  https://github.com/Darkosto/SkyFactory4Issues/issues/495 ? Unlike the previous report, this does not require a "locked" Filing Cabinet.

## Expected Behaviour
Items should be removed from the Transfer Node when moved into the Filing Cabinet.

## Steps to Reproduce
1. Set up a Filing Cabinet with Files for the item you want to dupe (tested with Wool and String).
2. Get a GPS Marker for the Filing Cabinet.
3. Place a Item Transfer Node, and insert the GPS Marker.
4. Place a single item in the Item Transfer Node.
5. Watch the count QUICKLY increase in the Filing Cabinet, but the item never leaves the Item Transfer Node.

**Comment by 7pmij** [comment]
Please fix very annoying

**Comment by Lothrazar** [comment]
Looks like things have changed on both mods since the original issue, now what happens is it just wont insert .  Which is at least not duping anymore. 
also see 
https://github.com/Lothrazar/Cyclic/issues/1126
and gif


![1119](https://user-images.githubusercontent.com/621529/58918945-30713580-86e1-11e9-8143-1a65323574c9.gif)
