### ISSUE TITLE
liquid xp to xp ratio?

### ISSUE THREAD

**Issue by resinate** [Lothrazar/Cyclic#1178]
is there a way to change how much exp 1mb is?

**Comment by Lothrazar** [comment]
its set at exactly 20:1 because when i was looking around thats what other mods were doing with their fluid exp .  

https://github.com/Lothrazar/Cyclic/blob/374be9e55f140a540d1c5c11b5a26dee722de216/src/main/java/com/lothrazar/cyclicmagic/block/exppylon/TileEntityXpPylon.java#L44


  //20mb per xp following convention set by EnderIO; OpenBlocks; and Reliquary https://github.com/PrinceOfAmber/Cyclic/issues/599
