### ISSUE TITLE
Support for non-vanilla torches?

### ISSUE THREAD

**Issue by bushbaby1234** [Lothrazar/Cyclic#1234]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2836

Mod Version: 1.12.2-1.19.14

Single Player or Server: Lan-world

Describe problem (what you were doing; what happened; what should have happened):

would it be possible to support the use of torches like the tinkers stone torches or integrated dynamics torches in the automatic torches and the torch launcher?

Log file link: N/A

Video/images/gifs (direct upload or link): N/A

If your bug is related to anything causing LAG you need to measure the lag by taking a sample https://minecraft.curseforge.com/projects/sampler

**Comment by Lothrazar** [comment]
non-critical issues like this wont be addressed in 1.12 at this point in the lifecycle. Working on brand new mods and 1.14+ ports  .

For torches, since it now consumes torches from your inventory and places them in the world, it would be misleading for players if it was converting stone torches to normal, or the item would have to remember all its content types.
