### ISSUE TITLE
Why do the Extended Inventory Armor Slots delete items placed inside them?

### ISSUE THREAD

**Issue by katubug** [Lothrazar/Cyclic#1236]
Minecraft Version: 1.12.12

Forge Version: forge-1.12.2-14.23.5.2846-universal

Mod Version: Cyclic-1.12.2-1.19.16

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):
I open my extended inventory and went to go place some armor in either my default armor slots or the backup ones. After several tries (I'm in creative testing stuff, so it's not a biiiig deal), I finally noticed the "click to delete" hoverover text.

My question is, why is this a feature? Intuitive use would suggest that placing an item in those slots would either equip it (if in the left column), or have it ready to swap to (if in the right). Removing items from either slot works as expected. Why not placing?

At the very least, I'd suggest having players be simply unable to click armor into those slots. Having it delete the armor just seems like it would cause a lot of issues due to unwary players.

**Comment by Lothrazar** [comment]
I basically use one for normal armor and one for backup.

Or sometimes the extra has my Elytra and some good armor, and the other has a diamond Block Reach chest . So i can swap armors,relog, and keep them safe instead of a chest and swap with one button . 

![armor1236](https://user-images.githubusercontent.com/621529/65819354-3929d200-e1d0-11e9-93e1-815d046c974c.gif)

**Comment by katubug** [comment]
I mean, I agree that the slots are cool, but I understand the potential uses for them - that's not the issue I meant. Here's an image:

https://gfycat.com/hopefultidyhadrosaurus

It's the "click to delete" functionality that I'm questioning. Intuition would suggest that one could place armor in those slots to "stock" it as a backup, to then be switched with your primary armor. Instead, attempting to put armor there deletes it. It took me a while to realize what was happening because I didn't see the "Click to Delete" tooltip.

**Comment by katubug** [comment]
I see that you've tagged this with more info needed - please let me know if I can provide you with any. I'm not sure what else to report. Thanks for your time! :)

**Comment by katubug** [comment]
Hi, sorry to bother. Did you still need more info on this? Please let me know what I can do.

**Comment by Lothrazar** [comment]
Thanks for your patience i know its been a while. 

I see whats happening in the GIF you made above how it dissappears. but i cant get it to do that no matter what i try.
on newest forge and mod versions
 
![1236](https://user-images.githubusercontent.com/621529/71564566-baa33180-2a57-11ea-9729-a952110d93d1.gif)

**Comment by Lothrazar** [comment]
if i click in the GAP in between, it does go away but it falls on the ground

**Comment by katubug** [comment]
No worries, thank you for your response! I haven't tested this in a while, but once I can get back to my desktop, I'll make sure it's not a mod conflict or user error.

**Comment by BabyGrootTheEpic** [comment]
Sorry if I'm not allowed to post since this is closed/old/made by someone else, this is my first post on this website.

The armor was being deleted because of JEI. katubug had JEI bookmarks on in the gif, and the bookmark section goes under the extended inventory armor section (you can tell by the right arrow just above it). The bookmarks section deletes any items you place in it when you have OP/Cheats on, just like the normal section to the right. To recreate this, just add something to the bookmarks (to do this press 'A' while hovering your mouse over an item) and then attempt to place any object (it doesn't have to be armor) into any of the slots, or just anywhere between the arrows at the top of the bookmarks and the bookmarks toggle button at the bottom left of the screen. If you turn them off with the metioned toggle button or by removing all bookmarks it will not delete any items.

Edited, 'cause I thought you were in minecraft version 1.7.10 for some reason. Doesn't change anything except terminology, I recreated it in 1.12.2.
