### ISSUE TITLE
[1.12.2] Max health conflict with any mod that changes the baseValue of player MAX_HEALTH attribute

### ISSUE THREAD

**Issue by notcake** [Lothrazar/Cyclic#1258]
Cyclic's max health system incorrectly assumes that the `MAX_HEALTH` attribute's base value never changes. Some mods increase player max health by calling `setBaseValue()`. When players reconnect or change dimension, Cyclic resets player health to the value last recorded by Cyclic, breaking the max health changes from those other mods.

This issue can be reproduced with MineKraft: Ultra:
```
player.getEntityAttribute(SharedMonsterAttributes.MAX_HEALTH).setBaseValue(maxHealth);
```
https://github.com/ChaosBuffalo/MKUltra/blob/eaedf9147e9b3a088c503ad9fe0946e47020acdf/src/main/java/com/chaosbuffalo/mkultra/core/PlayerData.java#L517

eg:

|                                                     | Max Health    | Base Value     | Cyclic attribute modifier | IPlayerExtendedProperties<br>.getMaxHealth()                   |
| --------------------------------------------------- | ------------- | -------------- | ------------------------- | -------------------------------------------------------------- |
| 1. Player starts off with 10 hearts                 | 10 hearts     | 10 hearts      | +0 hearts                 | 10 hearts<br>(`ItemHeartContainer.defaultHearts * 2`)          |
| 2. Player eats 10 Heart Containers                  | 20 hearts     | 10 hearts      | **+10 hearts**            | **20 hearts**<br>**(set in `ItemHeartContainer.onFoodEaten`)** |
| 3. Player chooses a class in MineKraft: Ultra<br>(Sun Icon, eg. Brawler class) | 45 hearts     | **35 hearts**  | +10 hearts                | 20 hearts                                                      |
| 4. Player enters nether                             | 20 hearts     | 35 hearts      | **-15 hearts**<br>(`EventPlayerData.onJoinWorld`<br>-> `UtilEntity.setMaxHealth`)            | 20 hearts                                                      |
| 5. Player unchooses their class in MineKraft: Ultra<br>(Forgetfulness Bread) | **-5 hearts** | **10 hearts**  | -15 hearts            | 20 hearts                                                      |

Note that after entering the nether the player's health may be temporarily more than their new max health.

--------------------------------------------------------------

Cyclic should avoid trying to track or set the overall player max health and should only track its own max health modifiers. 

A cheap fix could be to replace the usage of `.getBaseValue()` with a hardcoded 10 hearts (20 health) in `UtilEntity.getMaxHealth` and `UtilEntity.setMaxHealth`. `UtilEntity.getMaxHealth` returns incorrect values anyway since it only adds health modifiers from Cyclic and no other mods

See also https://github.com/Lothrazar/Cyclic/pull/870

Related to #1115

**Comment by BlueAgent** [comment]
So looked into this and it seems both [MineKraft: Ultra](https://github.com/ChaosBuffalo/MKUltra/blob/eaedf9147e9b3a088c503ad9fe0946e47020acdf/src/main/java/com/chaosbuffalo/mkultra/core/PlayerData.java#L533) and [Minestrappolation](https://github.com/MinestrapTeam/Minestrapp-1.12/blob/4cdcc170102e42cee9311b7953c9f439fcea52b1/main/java/minestrapp/event/MEventHandler.java#L102-L107) (#1115) use `setBaseValue`.

Using `setBaseValue` is kinda flaky cause only one mod can be using that method in a pack or it'll conflict.
Prior to #870 Cyclic was using setBaseValue which was conflicting with other mods hence the switch to using attributes. This situation was accounted for in #870, in it two solutions were proposed, the first one (which depends on getBaseHealth) was chosen since it had less changes. The second solution (which is agonstic to getBaseHealth) was deemed too much of a change at the time, but it would prevent conflicts with other mods changing the base health.

Along with the misleading behaviour pointed out in #870 and here (config for startingHealth, the set max health commands and method names in the code) probably indicates some change is a good idea.

To prevent issues like this in the future we could do the following:
Instead of having the configuration be `startingHealth` with default of `20`, we could change it to be `startingHealthModifier` with a default of 0 as well as switch from basing things around max health to purely using a health modifier instead. Will look into this.

**Comment by Lothrazar** [comment]
Resolved by https://github.com/Lothrazar/Cyclic/pull/1264 . it now stores a modifier instead of editing raw values.

More compatible this way, and if all health items and commands are changed the modifier is zero and not used
