### ISSUE TITLE
Ender Book suddenly fails

### ISSUE THREAD

**Issue by lynaevm** [Lothrazar/Cyclic#880]
Minecraft version & Mod Version:
Enigmatica 2 expert -- whatever is in that

Single player or Server:
Server

Describe problem (what you were doing / what happened):
I have been using the Ender Book for several days now, but now it suddenly fails to teleport me.  I have plenty of xp and get no failure message.  I get the purple ender "sparkles" that usually precede the teleport, but no actual movement.  Have tried reloading the game, removing all equipment, trying multiple destinations in different dimensions... nothing.  No crash or failure message.  Other people on the server still successfully using the book.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
Any error info in any of the log files? 

It should work even if chunk is unloaded, but that could be related if its really far?

**Comment by lynaevm** [comment]
Server admin said there was a "trying to move to fast" error once,but not other times that I tried it.  I tried it just moving accross the room, so chunk unloading couldn't have been the problem.  Anything else you would like me to try?

**Comment by PrinceOfAmber** [comment]
What version of the mod is in your current pack? Looks like i made some changes and improvements to ender book on 1.15.13 , i wonder if this was before or after.
https://github.com/PrinceOfAmber/Cyclic/issues/857

Its possible that the server has some sort of anti-flight or anti-cheat mode where it thinks you are flying/hacking.. .at least when i google "trying to move to fast" thats  what people are saying

**Comment by kvalek** [comment]
I encountered this bug aswell on my personal server. It is running Enigmatica 2 version 1.46 which has Cyclic version 1.17.0.

The Ender book suddenly stopped working for me after using it extensively since i started. Looking at the logs, it doesn't report any warnings or errors (usually MC will report "Warning: player moved wrongly" whenever someone uses an ender book).
The odd thing is it only applies to my character. It still works for other players on my server. I tried draining my XP and gaining new, with no effect and restarting the server. What i did notice though was that my XP drained when i tried using it and it didnt work.

As you say in your last comment, it might be because of an anti-cheat mode, but i am OP on the server and allow-flight is set to true in server.properties.

**Comment by Ghost942** [comment]
I too am having the same issue, but with updated versions.

Enigmatica 2 Expert Server - version 1.44 on Minecraft 1.12.2
Cyclic version 1.12.2-1.17.10

Same scenario: Book fails to teleport, same purple sparks and teleport noise, but no actual movement. Still works for other players on the same server.

**Comment by Lothrazar** [comment]
Thanks for updates. newer versions look pretty stable.  as well re https://github.com/Lothrazar/Cyclic/issues/1094 

If any  issues happen on current versions we can revisit

**Comment by katubug** [comment]
One of my players seems to be having this same issue. I personally cannot replicate.

She has 137 levels and has tested multiple different waypoints with no luck. We tried the setting to creative and back, and the opping and back - neither worked. Dying did, though. So I suspect it's the same issue.

Cyclic version: Cyclic-1.12.2-1.19.11
Forge version: forge-1.12.2-14.23.5.2838-universal
Server log: https://pastebin.com/TWPM0gdw

Full modlist is at the bottom of this post: http://enthusiasticraft.cf/modpack-update-1-5-1/
