### ISSUE TITLE
Wireless Receiver Not Deactivating

### ISSUE THREAD

**Issue by medtryx** [Lothrazar/Cyclic#951]
Minecraft version & Mod Version:

 Forge Mod Loader version 14.23.5.2770 for Minecraft 1.12.2

Cyclic 1.17.3

Single player or Server: 

Single Player

Describe problem (what you were doing / what happened):

If a wireless redstone transmitter is placed adjacent to a wireless redstone receiver with a single non-transparent block connecting them, the wireless receiver will not stop outputting a redstone signal even when the transmitter is toggled off. If the transmitter is broken before the block connecting them is broken, the receiver will not stop transmitting until broken or the transmitter is replaced. This also happens if the transmitter is placed directly next to the receiver. 

Crash log (if any):

This does not cause a crash and does not show any issues in the server log file. I discovered this in the Stoneblock modpack and was able to replicate it with only the latest instances of Forge and Cyclic installed on a custom profile.

**Comment by PrinceOfAmber** [comment]
This took me a minute to investigate, because it works fine in most arrangement.  The key is if they are adjacent and connected.


The reasons this happens is it because its a loop, the receiver is powered, and it outputs to all sides, and it goes through that one block to the transmitter and that loops around.

If you replace the one solid block with redstone dust it makes lots of sense , see video below 

https://i.imgur.com/PiIVXql.gifv

**Comment by medtryx** [comment]
> This took me a minute to investigate, because it works fine in most arrangement. The key is if they are adjacent and connected.
> 
> The reasons this happens is it because its a loop, the receiver is powered, and it outputs to all sides, and it goes through that one block to the transmitter and that loops around.
> 
> If you replace the one solid block with redstone dust it makes lots of sense , see video below
> 
> https://i.imgur.com/PiIVXql.gifv

That make's sense. However, the receiver will continue output when it's transmitter is broken, even with block updates to the receiver.
