### ISSUE TITLE
 java.lang.NoClassDefFoundError: ft crash

### ISSUE THREAD

**Issue by mrdeadlocked** [Lothrazar/Cyclic#963]
Minecraft version & Mod Version:
1.12.2 FOrge 14.23.5.2772
Cyclic-1.12.2-1.17.4.jar

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
Crash when adding cyclic to modpack. I can go back to Cyclic-1.12.2-1.16.10.jar and crash goes away

Crash log (if any):

[crash-2018-10-25_09.55.40-client.txt](https://github.com/PrinceOfAmber/Cyclic/files/2515283/crash-2018-10-25_09.55.40-client.txt)
(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by PrinceOfAmber** [comment]
This appears at first to be a bug in the newest forge versions.

According to the site when i click 'show all versoins' http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html

14.23.5.2768  is "release build" since it has a star, and 2772 has a bug icon next to it.


Is it fixed when you roll back to this previous forge build?

**Comment by mrdeadlocked** [comment]
I just tested 2768-2771 with my mod pack and newest cyclic.

2771
[crash-2018-10-25_15.39.33-client.txt](https://github.com/PrinceOfAmber/Cyclic/files/2516467/crash-2018-10-25_15.39.33-client.txt)
2770
[crash-2018-10-25_15.38.31-client.txt](https://github.com/PrinceOfAmber/Cyclic/files/2516468/crash-2018-10-25_15.38.31-client.txt)
2769
[crash-2018-10-25_15.37.20-client.txt](https://github.com/PrinceOfAmber/Cyclic/files/2516469/crash-2018-10-25_15.37.20-client.txt)
2768
[crash-2018-10-25_15.35.31-client.txt](https://github.com/PrinceOfAmber/Cyclic/files/2516470/crash-2018-10-25_15.35.31-client.txt)


2768 + 2772 (alone with just cyclic in multimc) work fine. I'm not sure what to add. I guess it's not your mod exclusively. I found this issue by putting a handful of mods into my updated modpack until I got the crash. Yours was the one causing it but it doesn't do it by itself. 

![image](https://user-images.githubusercontent.com/461352/47526360-88071300-d86d-11e8-9e31-5c0f8dcb317d.png)

**Comment by PrinceOfAmber** [comment]
Hmm, yeah definately something weird going on .. but i dont know where to start looking.   Often with stuff like this its a Coremod, where it has dived into the base code and changes things, so other mods using it might have an issue, foam fix is an example but its usually pretty gentle. 


If you can find out the crash with just 2 mods (so cyclic + forge + other) , then thats something to go on since one of those mods is the problem.

**Comment by mrdeadlocked** [comment]
I'll start digging through and see what I can find out.

**Comment by mrdeadlocked** [comment]
Found it. Cyclic, Forge, and Fast Trading cause it.
[crash-2018-10-26_11.00.55-client.txt](https://github.com/PrinceOfAmber/Cyclic/files/2519720/crash-2018-10-26_11.00.55-client.txt)

**Comment by PrinceOfAmber** [comment]
Thanks ill do some testing https://www.curseforge.com/minecraft/mc-mods/fasttrading

**Comment by PrinceOfAmber** [comment]
I couldnt find an issue tracker on their end but i commented and asked about it  on teh curseforge page ,, maybe other author can help out https://minecraft.curseforge.com/projects/fasttrading

**Comment by Lothrazar** [comment]
fasttrading does not have an issue tracker or source code so theres nothing i can do. I dont do any crazy ASM or core modding so i have to just leave this as it is.

Also they are not responding
![no response](https://user-images.githubusercontent.com/621529/54095302-d4a64300-4363-11e9-9d07-a9f199c3819f.PNG)


I have to assume its the other mod since Cyclic is in dozens of huge modpacks with no issues.
